src/config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  get '/signup', to: 'users#new'
  resources :users
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  get '/confirm', to:'static_pages#confirm'
  get '/goals', to:'static_pages#goals'
  resources :tasks do
    collection do
      get :change
    end
  end
  resources :groups do
    member do
      post :change, :add
    end
    get "search", on: :collection
  end
  resources :user_groups, only: [:edit,:update,:destroy]
  resources :teams do
    member do
      post :add
      get :search, :confirm
    end
    post "change", on: :collection
  end
  resources :user_teams, only: [:destroy]
  resources :monthly_goals do
    collection do
      post :change, :store
    end
  end
  resources :weekly_goals do
    collection do
      post :store, :week, :whose
    end
  end
  match "*path" => "application#error404", via: :all
end

src/app/models/weekly_goal.rb
class WeeklyGoal < ApplicationRecord
    belongs_to :team

    with_options presence: true do
        validates :team_id
        validates :month
        validates :whose
        validates :week, inclusion: { in: %w(１週目 ２週目 ３週目 ４週目 ５週目) }
        validates :plan, length: { maximum: 500 }
        validates :action, length: { maximum: 500 }
    end
    validates :output, length: { maximum: 500 }
    validates :review, length: {maximum: 500}
    
    attr_accessor :check

end

src/app/models/weekly_goals_form.rb
class WeeklyGoalsForm
    include ActiveModel::Model
    
    GOAL_NUM = 5
    attr_accessor :collection,:whose,:week
    validates :week, presence: true
    validates :whose, presence: true


    def initialize(goals_params = [],other_params = [])
        if goals_params.present?
            self.collection = goals_params.map do |value|
                if value['check'] == "1"
                    WeeklyGoal.new(
                        month: value['month'].to_datetime,
                        team_id: value['team_id'],
                        week: other_params['week'],
                        whose: other_params['whose'],
                        plan: value['plan'],
                        action: value['action'],
                    )
                else
                    next
                end
            end.compact
            self.week = other_params['week']
            self.whose = other_params['whose']
        else
            self.collection = GOAL_NUM.times.map{ WeeklyGoal.new }
        end
    end

    def save
        is_success = true
        ActiveRecord::Base.transaction do
            collection.each do |result|
                is_success = false unless result.save
            end
            raise ActiveRecord::RecordInvalid unless is_success
        end
        rescue
            ActiveRecord::RecordInvalid
        ensure
            return is_success  
    end
    

end

src/app/controllers/weekly_goals_controller.rb
class WeeklyGoalsController < ApplicationController
    before_action :logged_in_user
    before_action :group_member
    before_action :store_date, except:[:store]

    def store
        session[:date] = params[:date]
        redirect_to (weekly_create_or_edit?(session[:date]) ? weekly_goals_path : new_weekly_goal_path)
    end

    def new
        @goals_form = WeeklyGoalsForm.new()      
    end

    def create
        @goals_form = WeeklyGoalsForm.new(goals_params,date_params) 
        if @goals_form.save
            flash[:success] = "Weekly Goals created"
            session[:week] = @goals_form.week
            session[:whose] = @goals_form.whose
            redirect_to weekly_goals_path
        else
            flash.now[:danger] = 'There is an error in the entry of plan or action'
            render :new
        end
    end

    def index
        if session[:week] && session[:whose]
            @goals = stored_team.weekly_goals.where(month:stored_date,week:session[:week],whose:session[:whose]).order(updated_at: :desc)
        elsif session[:week]
            @goals = stored_team.weekly_goals.where(month:stored_date,week:session[:week]).order(updated_at: :desc)
        elsif session[:whose]
            @goals = stored_team.weekly_goals.where(month:stored_date,whose:session[:whose]).order(updated_at: :desc)
        else
            session[:week] = default_week(stored_team,stored_date)
            session[:whose] = default_whose(stored_team,stored_date)
            @goals = stored_team.weekly_goals.where(month:stored_date,week:session[:week],whose:session[:whose]).order(updated_at: :desc)
        end
    end

    def show
        @weekly_goal = WeeklyGoal.find(params[:id])
        render 'edit'
    end

    def week
        session[:week]  = params[:week]
        redirect_to weekly_goals_path
    end

    def whose
        session[:whose]  = params[:whose]
        redirect_to weekly_goals_path
    end

    def edit
        @weekly_goal = WeeklyGoal.find(params[:id])
    end

    def update
        @weekly_goal = WeeklyGoal.find(params[:id])
        if @weekly_goal.update(edit_goals_params)
            flash[:success] = "Weekly Goal updated"
            redirect_to weekly_goals_path
        else
            render 'edit'
        end
    end

    def destroy
        @weekly_goal = WeeklyGoal.find(params[:id])
        week = @weekly_goal.week
        @weekly_goal.destroy
        flash[:success] = "Weekly Goal deleted"
        @weekly_goal_week = stored_team.weekly_goals.where(month:stored_date,week:week)
        @weekly_goal = stored_team.weekly_goals.where(month:stored_date)
        if @weekly_goal_week.exists?
            redirect_to weekly_goals_path
        elsif @weekly_goal.exists?
            session.delete(:week)
            session.delete(:whose)
            redirect_to weekly_goals_path
        else
            redirect_to goals_path
        end
    end

    private
        def goals_params
            params.require(:goals)
        end

        def date_params
            params.require(:weekly_goals_form)
        end

        def edit_goals_params
            params.require(:weekly_goal).permit(:team_id,:month,:week,:whose,:plan,:action,:output,:review)
        end

end

src/app/helpers/weekly_goals_helper.rb
module WeeklyGoalsHelper
    def weekly_create_or_edit?(d)
        d = d.to_datetime()
        goals = stored_team.weekly_goals.where(month:d)
        goals.exists? ? true : false
    end

    def get_weeks(team,month)
        weeks = team.weekly_goals.select(:week).where(month:month).distinct
    end

    def get_whose(team,month)
        whose = team.weekly_goals.select(:whose).where(month:month).distinct
    end

    def get_whose_name(id)
        id = "0" if id.nil?
        id == "0" ? stored_team.name : User.find_by(id:id).name
    end

    def week_of_month(date)
        first_week = (date - (date.day - 1)).cweek
        this_week = date.cweek
      
        if this_week < first_week
          
          if date.month == 12
            return (week_of_month(date - 7) + 1).to_s().tr("A-Z0-9","Ａ-Ｚ０-９")
            
          else
            return (this_week + 1).to_s().tr("A-Z0-9","Ａ-Ｚ０-９")
          end
        end
        
        return (this_week - first_week + 1).to_s().tr("A-Z0-9","Ａ-Ｚ０-９")
    end

    def default_week(team,date)
        week = week_of_month(Date.today) + "週目"
        goals = team.weekly_goals.where(month:date.to_datetime(),week:week)
        return goals.exists? ? week : team.weekly_goals.where(month:date.to_datetime()).first.week
    end

    def default_whose(team,date)
        id = team.weekly_goals.where(month:date.to_datetime()).first.whose
        team_goals = team.weekly_goals.where(month:date.to_datetime())
        user_goals = team.weekly_goals.where(whose:current_user.id,month:date.to_datetime())
        if user_goals.exists?
            return current_user.id
        elsif team_goals.exists?
            return "0"
        else
            return id
        end
    end
end

src/app/views/weekly_goals/edit.html.erb
<% provide(:title, "Weekly Goals") %>
<div class="edit-goals">
    <div class="row">
        <div class="col-md-6 col-md-offset-3 woocommerce">
            <nav class="navbar navbar-default">
                <div class="container-fluid">
                    <div class="navbar-header">
                        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        </button>
                        <div class="navbar-header navbar-brand"><%= stored_team.name if !my_task?() %></div>
                        <div class="navbar-header navbar-brand"><%= "#{stored_date.year}/#{stored_date.month}" %></div>
                    </div>
                    
                    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                        <ul class="nav navbar-nav">
                            <li><%= link_to "Delete Goal", @weekly_goal, method: :delete, data: { confirm: "Delete this weekly goal ?" } %></li>
                        </ul>
                    </div>
                </div>

            </nav>            

            <%= form_with(model: @weekly_goal, local: true) do |f| %>
                <%= render 'shared/error_messages', object: f.object %>
                <%= f.hidden_field :team_id, value:stored_team.id %>
                <%= f.hidden_field :month, value:stored_date %>
                <div class="row">
                    <div class="col-md-6">
                        <%= f.label :whose %>
                        <%= f.select :whose, [[stored_team.name,0], [current_user.name,current_user.id]],{}, {class: 'form-control'} %>
                    </div>
                    <div class="col-md-6">
                        <%= f.label :week %>
                        <%= f.select :week, ["１週目", "２週目", "３週目", "４週目", "５週目"],{}, {class: 'form-control'} %>
                    </div>
                </div>
                
                <%= f.label :plan %>
                <%= f.text_field :plan, class: 'form-control' %>

                <%= f.label :action %>
                <%= f.text_field :action, class: 'form-control' %>

                <%= f.label :output %>
                <%= f.text_area :output, class: 'form-control' %>

                <%= f.label :review %>
                <%= f.text_area :review, class: 'form-control' %>

                <%= f.submit "Post", class: "btn btn-primary btn-block btn-lg mb-4 mt-3" %>
                
            <% end %>
        </div>
    </div>
</div>

src/app/views/weekly_goals/index.html.erb
<% provide(:title, "Weekly Goals") %>
<div class="w-goals">
    <nav class="navbar navbar-default">
        <div class="container-fluid">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                </button>

                <div class="navbar-header navbar-brand"><%= link_to stored_team.name, goals_path if !my_task?() %></div>
                <% if !my_task?() %>
                    <div class="navbar-header navbar-brand"><%= "#{stored_date.year}/#{stored_date.month}" %></div>
                <% else %>
                    <div class="navbar-header navbar-brand"><%= link_to "#{stored_date.year}/#{stored_date.month}", goals_path %></div>
                <% end %>
            </div>

            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav">
                    <li><%= link_to "Add Goal", new_weekly_goal_path %></li>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%= session[:week] %><span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            <% get_weeks(stored_team,stored_date).each do |week| %>
                                <li><%= link_to week.week, {controller: "weekly_goals", action: "week", week:week.week},method: :post %></li>
                            <% end %>
                        </ul>
                    </li>
                    <% if !my_task?() %>
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%= get_whose_name(session[:whose]) %><span class="caret"></span></a>
                            <ul class="dropdown-menu">
                                <% get_whose(stored_team,stored_date).each do |whose| %>
                                    <li><%= link_to get_whose_name(whose.whose), {controller: "weekly_goals", action: "whose", whose:whose.whose},method: :post %></li>
                                <% end %>
                            </ul>
                        </li>
                    <% end %>
                </ul>
            </div>
        </div>
    </nav>
    <% @goals.each do |goal| %>
        <table class="table table-bordered">
            <tbody>
                    <tr>
                        <td>
                            <label>Plan</label>
                            <p><%= goal.plan %></p>
                        </td>
                        <td>
                            <label>Output</label>
                            <%= link_to "Edit", edit_weekly_goal_path(goal) %>
                            <p><%= goal.output %></p>
                        </td>
                    </tr>
                    <tr>
                        <td>
                            <label>Action</label>
                            <p><%= goal.action %></p>
                        </td>
                        <td>
                            <label>Review</label>
                            <p><%= goal.review %></p>
                        </td>
                    </tr>
            </tbody>
        </table>
    <% end %>
</div>

src/app/views/weekly_goals/new.html.erb
<% provide(:title, "Weekly Goals") %>
<div class="new-goals">
    <%= form_with model: @goals_form, url: weekly_goals_path,class:"form-horizontal", local: true do |form| %>
        <nav class="navbar navbar-default">
            <div class="container-fluid">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    </button>

                    <div class="navbar-header navbar-brand"><%= stored_team.name if !my_task?() %></div>
                    <div class="navbar-header navbar-brand"><%= "#{stored_date.year}/#{stored_date.month}" %></div>
                    <% if !my_task?() %>
                        <div class="navbar-header navbar-brand form-seelct">
                            <%= form.label :whose,class:"control-label sr-only" %>
                            <%= form.select :whose, [[stored_team.name,0], [current_user.name,current_user.id]],{}, class: 'form-control' %>
                        </div>
                    <% else %>
                        <%= form.hidden_field :whose, value:0 %>
                    <% end %>
                    <div class="navbar-header navbar-brand form-seelct">
                        <%= form.label :week,class:"control-label sr-only" %>
                        <%= form.select :week, ["１週目", "２週目", "３週目", "４週目", "５週目"],{}, class: 'form-control' %>
                    </div>
                </div>

            </div>
        </nav>

        <table class="table">
            <tbody>
                <% @goals_form.collection.each do |goal|%>
                    <tr>
                        <%= fields_for 'goals[]', goal do |f| %>
                            <td class="check-goal">
                                <%= f.label :check, class: "checkbox inline"%>
                                <%= f.check_box :check ,{ checked: (goal == @goals_form.collection[0] ? true : false) } %>
                            </td>
                            <%= f.hidden_field :month, value:stored_date %>
                            <%= f.hidden_field :team_id, value:stored_team.id %>

                            <td class="other-form">
                                <%= f.label :plan, class:"col-sm-2 control-label" %>
                                <div class="col-sm-10">
                                    <%= f.text_field :plan, class: 'form-control' %>
                                </div>
                            </td>
                            <td class="other-form">
                                <%= f.label :action, class:"col-sm-2 control-label" %>
                                <div class="col-sm-10">
                                    <%= f.text_field :action, class: 'form-control' %>
                                </div>
                            </td>

                        <% end %>
                    </tr>
                <% end %>
            </tbody>
        </table>
        <%= form.submit "Post", class: "btn btn-primary" %>
    <% end %>
</div>