src/config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  get '/signup', to: 'users#new'
  resources :users
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  get '/confirm', to:'static_pages#confirm'
  get '/goals', to:'static_pages#goals'
  resources :tasks do
    collection do
      get :change
    end
  end
  resources :groups do
    member do
      post :change, :add
    end
    get "search", on: :collection
  end
  resources :user_groups, only: [:edit,:update,:destroy]
  resources :teams do
    member do
      post :add
      get :search, :confirm
    end
    post "change", on: :collection
  end
  resources :user_teams, only: [:destroy]
  resources :monthly_goals do
    collection do
      post :change, :store
    end
  end
  resources :weekly_goals do
    collection do
      post :store, :week, :whose
    end
  end
  match "*path" => "application#error404", via: :all
end

src/app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class=" alert-danger">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

src/app/views/shared/_g_tab.html.erb
<div class="user-navbar">
  <nav class="navbar navbar-default">
    <div class="container-fluid">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <div class="navbar-header navbar-brand"><%= object.name %></div>
      </div>

      

      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav">
            <li class=<%= 'active' if current_page?(object) %>><%= link_to "Show Member", object %></li>
            <li class=<%= 'active' if current_page?(search_groups_path) %>><%= link_to "Add User", {controller: "groups", action: "search", id:object.id},method: :get %></li>
            <li class=<%= 'active' if current_page?(edit_group_path(object)) %>><%= link_to "Change Name", edit_group_path(object) %></li>
            <li><%= link_to "Delete Group", group_path(object), method: :delete, data: {confirm: "If you delete this group, the task will also be deleted. Are you sure?"} %></li>
          </ul>
      </div>
    </div>
  </nav>
</div>

src/app/views/shared/_p_tab.html.erb
<div class="user-navbar">
  <nav class="navbar navbar-default">
    <div class="container-fluid">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <div class="navbar-header navbar-brand"><%= object.name %></div>
      </div>
      

      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav">
              <li class=<%= 'active' if current_page?(object) %>><%= link_to 'Joined Group',object %></li>
              <li class=<%= 'active' if current_page?(new_group_path) %>><%= link_to 'Create Group', new_group_path %></li>
              <li class=<%= 'active' if current_page?(edit_user_path(object)) %>><%= link_to 'Edit Profile', edit_user_path(object) %></li>
              <li><%= link_to 'Logout',logout_path, method: :delete %></li>
          </ul>
      </div>
    </div>
  </nav>
</div>

src/app/views/shared/_t_tab.html.erb
<nav class="navbar navbar-default">
    <div class="container-fluid">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            </button>
            <div class="navbar-header navbar-brand"><%= @team.name %></div>
        </div>

        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav">
                <li class=<%= 'active' if current_page?(@team) %>><%= link_to 'Show Member',@team %></li>
                <li class=<%= 'active' if current_page?(edit_team_path(@team)) %>><%= link_to 'Change Name',edit_team_path(@team) %></li>
                <li class=<%= 'active' if current_page?(search_team_path(@team)) %>><%= link_to 'Add User',search_team_path(@team) %></li>
                <li><%= link_to "Delete Team", team_path(@team), method: :delete, data: {confirm: "If you delete this team, the task will also be deleted. Are you sure ?"} %></li>
            </ul>
        </div>
    </div>
</nav>

src/app/views/shared/_tab.html.erb
<ul class="nav nav-tabs nav-justified">
    <li role="presentation" class=<%= 'active' if current_page?(root_path) %> >   
        <%= link_to (my_task?()? 'Home' : current_team.name), root_path, class:"nav-link "%>
    </li>
    <li role="presentation" class=<%= 'active' if current_page?(tasks_path) %>>
        <%= link_to 'All Task', tasks_path, class:"nav-link " %>
    </li>
    <li role="presentation" class=<%= 'active' if current_page?(new_task_path) %>>
        <%= link_to 'Create Task', new_task_path, class:"nav-link" %>
    </li>
    <% if !my_task?() %>
        <% if has_teams?() %>
            <li role="presentation" class=<%= 'active' if !%w[tasks root new_task].any? { |name| current_page?(send("#{name}_path")) } %>>
                <%= link_to 'Team Detail', team_path(current_team), class:"nav-link" %>
            </li>
        <% end %>
        <li role="presentation" class="dropdown">
            <a class="dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">
                Switch Task <span class="caret"></span>
            </a>
            <ul class="dropdown-menu">
                <li>
                    <%= link_to "My Tasks", {controller: "tasks", action: "change", change:1},method: :get %>
                </li>
                <li>
                    <%= link_to "#{current_team.name} Tasks", {controller: "tasks", action: "change", change:0},method: :get %>
                </li>
            </ul>
        </li>
    <% end %>
</ul>