src/config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  get '/signup', to: 'users#new'
  resources :users
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  get '/confirm', to:'static_pages#confirm'
  get '/goals', to:'static_pages#goals'
  resources :tasks do
    collection do
      get :change
    end
  end
  resources :groups do
    member do
      post :change, :add
    end
    get "search", on: :collection
  end
  resources :user_groups, only: [:edit,:update,:destroy]
  resources :teams do
    member do
      post :add
      get :search, :confirm
    end
    post "change", on: :collection
  end
  resources :user_teams, only: [:destroy]
  resources :monthly_goals do
    collection do
      post :change, :store
    end
  end
  resources :weekly_goals do
    collection do
      post :store, :week, :whose
    end
  end
  match "*path" => "application#error404", via: :all
end

src/app/views/layouts/_header.html.erb
<nav class="navbar navbar-default navbar-fixed-top">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            </button>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
            <ul class="nav navbar-nav navbar-right">
                <% if !my_task?() %>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Tasks <span class="caret"></span></a>
                            <ul class="dropdown-menu">
                                <% my_teams.each do |team| %>
                                    <li><%= link_to team.name, {controller: "teams", action: "change", id:team.id},method: :post %></li>
                                <% end %>
                                <li role="separator" class="divider"></li>
                                <li><%= link_to "Create Team", new_team_path %></li>
                            </ul>
                    </li>
                <% else %>
                    <% my_teams.each do |team| %>
                        <li><%= link_to "Tasks", {controller: "teams", action: "change", id:team.id},method: :post %></li>
                    <% end %>
                <% end %>
                <% if my_task?() %>
                    <% current_group.teams.each do |team| %>
                        <li class="nav-item"><%= link_to "Goals", {controller: "monthly_goals", action: "change", team_id:team.id, year:Date.today.year},method: :post %></li>
                    <% end %>
                <% else %>
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Goals <span class="caret"></span></a>
                                <ul class="dropdown-menu">
                                    <% current_group.teams.each do |team| %>
                                        <li><%= link_to team.name, {controller: "monthly_goals", action: "change", team_id:team.id, year:Date.today.year},method: :post %></li>
                                    <% end %>
                                </ul>
                        </li>
                <% end %>
                <li class="nav-item"><%= link_to current_user.name, current_user, class:"nav-link" %></li>
            </ul>
        </div>
    </div>
</nav>

src/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    
  </head>
  <body style="zoom: 1;">    
    <% if logged_in? %>
        <%= render 'layouts/header' %>
    <% end %>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end%>
      <%= yield %>
    </div>
  </body>
</html>